### ISSUE TITLE
Add support for `poem-openapi`

### ISSUE THREAD

**Issue by DDtKey** [DDtKey/poem-grants#2]
It is necessary to add support for `poem-openapi` (with `#[OpenApi]` macro) to `poem-grants`

**Comment by Soufian20** [comment]
Any updates on that?

**Comment by DDtKey** [comment]
@Soufian20 sorry for such large delay 😔  
I'll try to dedicate time for finishing in this month & publish stable version

**Comment by DDtKey** [comment]
Hey @Soufian20 I've published version with `poem-openapi` support, it's under `beta.2` - but ready to use. The `beta` is used here only due to fact that I'm currently preparing large update of `{framework}-grants` crates and it will have some additional improvements & will be easier to maintain.
